### ISSUE TITLE
Using the class doesn't return what it should

### ISSUE THREAD

**Issue by thamathar** [nthdeveloper/RichTextStripper#1] opened 2018-12-07 11:21 UTC
Hi, I have this RTF that has been done by the Control RichTextBox from VB (did try to put it on the RichTextBox of WPF and such gets what it should)

> {\rtf1\ansi\ansicpg1252\deff0\deflang2070{\fonttbl{\f0\fmodern\fprq6\fcharset134 SimSun;}{\f1\fnil\fcharset0 MS Sans Serif;}}  \viewkind4\uc1\pard\lang2052\f0\fs17\'b7\'f2\'c8\'cb\'b7\'eb\'b7\'f2\'c8\'cb6346\'b8\'f6\'ba\'ec\'b5\'c4\'b9\'f0\'bb\'a8\lang2070\f1   \par }

It should return 

> 夫人冯夫人6346个红的桂花~

This is what I get

> ·òÈË·ë·òÈË6346¸öºìµÄ¹ð»¨

**Comment by nthdeveloper** [comment] 2018-12-07 16:16
Hi, it seems you are using Simplified Chinese encoding. I have checked the charset-code page mapping and it seems to be correct. I have given the RTF content to the component and got a very strange stripped text. But when I add a RichTextBox on my form and enter the original text into it (夫人冯夫人6346个红的桂花~) I got a text with mostly contains "?" character. I think my Visual Studio can not display it in debug windows. 
Can you directly pass the RTF output of RichTextBox to the componenet and check the result?
Something like this;

`string _text = RichTextStripper.StripRichTextFormat(richTextBox1.Rtf);`

**Comment by thamathar** [comment] 2018-12-07 16:43
Hi, I hope that is this that I did understood that you wanted.

Have this code to test.


```
try
{
	string tempString = String.Empty;
	using (var con = new SqlConnection("SQLString"))
	{
		con.Open();
		{
			using (var cmd = con.CreateCommand())
			{
				cmd.CommandText = "select traduçao as tradu from artigos where Cod_Art='01010066'";
				using (var dr = cmd.ExecuteReader())
				{
					dr.Read();
					tempString = dr["tradu"].ToString();
				}
			}
		}
	}
	this.RichTextBoxTest.Rtf = tempString;
	string testString = this.RichTextBoxTest.Text;
	string textRich = RichTextStripper.StripRichTextFormat(this.RichTextBoxTest.Rtf);
	string teste = "";
}
catch (Exception ex)
{

}
```


This is what the variable have:

this.RichTextBoxTest.Rtf -> {\rtf1\ansi\ansicpg1252\deff0\deflang2070{\fonttbl{\f0\fmodern\fprq6\fcharset134 SimSun;}{\f1\fnil\fcharset0 MS Sans Serif;}}
\viewkind4\uc1\pard\lang2052\f0\fs17\'b7\'f2\'c8\'cb\'b7\'eb\'b7\'f2\'c8\'cb6346\'b8\'f6\'ba\'ec\'b5\'c4\'b9\'f0\'bb\'a8\lang2070\f1\par
}


testString -> 夫人冯夫人6346个红的桂花

textRich -> ??????????6346??????????

**Comment by srutzky** [comment] 2018-12-14 20:00
Hi there. The problem is simply that the code has no concept of [Double-Byte Character Sets (DBCS)](https://en.wikipedia.org/wiki/DBCS); it assumes that all encodings are Single-Byte. There are at least four 8-bit DBCS encodings supported by Windows and SQL Server, and the O.P. here is trying to use one of them. "charset134" refers to GB2312, which equates to "ANSI/OEM Simplified Chinese (PRC, Singapore); Chinese Simplified (GB2312)" / Code Page 936 (according to the Microsoft page for [Code Page Identifiers](https://docs.microsoft.com/en-us/windows/desktop/intl/code-page-identifiers)).

I have a fix for this issue working locally (the output I get is: ` 夫人冯夫人6346个红的桂花` ) and just need to create a PR for it.

P.S. This issue relates to the following StackExchange Q & A: [SQL Function, get value to send to CLR](https://dba.stackexchange.com/questions/224997/sql-function-get-value-to-send-to-clr) (it was asked only because the O.P. couldn't get this working for the GB2312 / Simplified Chinese encoding).

**Comment by thamathar** [comment] 2018-12-17 10:47
Many thanks @srutzky for the help :D

**Closed as completed** 2018-12-28 15:06 UTC
